---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  # N.B. this secret must live in the cert-manager namespace
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <CLOUDFLARE API TOKEN HERE>
